/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "tertiary-fixed": "#93f7ba",
        "primary": "#0047a9",
        "secondary-fixed": "#ffdcc2",
        "on-surface-variant": "#424654",
        "on-primary": "#ffffff",
        "surface-container": "#ebeef3",
        "outline": "#737785",
        "secondary-fixed-dim": "#ffb77a",
        "secondary": "#8f4e00",
        "inverse-on-surface": "#eef1f6",
        "tertiary-container": "#007445",
        "on-error": "#ffffff",
        "background": "#f7f9ff",
        "surface-dim": "#d7dadf",
        "on-primary-container": "#dae2ff",
        "on-primary-fixed-variant": "#00419d",
        "on-surface": "#181c20",
        "primary-fixed": "#d9e2ff",
        "surface-container-lowest": "#ffffff",
        "primary-container": "#0b5ed7",
        "on-secondary-fixed": "#2e1500",
        "on-secondary-fixed-variant": "#6d3a00",
        "outline-variant": "#c2c6d6",
        "surface-tint": "#0057cc",
        "error": "#ba1a1a",
        "primary-fixed-dim": "#b0c6ff",
        "surface-container-high": "#e5e8ee",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#93f7ba",
        "on-error-container": "#93000a",
        "surface-container-low": "#f1f4f9",
        "on-secondary": "#ffffff",
        "error-container": "#ffdad6",
        "secondary-container": "#fe9832",
        "inverse-primary": "#b0c6ff",
        "surface": "#f7f9ff",
        "surface-variant": "#e0e3e8",
        "tertiary-fixed-dim": "#77da9f",
        "on-background": "#181c20",
        "on-secondary-container": "#683700",
        "on-tertiary-fixed-variant": "#00522f",
        "surface-container-highest": "#e0e3e8",
        "tertiary": "#005934",
        "on-primary-fixed": "#001945",
        "inverse-surface": "#2d3135",
        "on-tertiary-fixed": "#002110",
        "surface-bright": "#f7f9ff"
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
        headline: ['Inter', 'Noto Sans Devanagari', 'sans-serif'],
        body: ['Inter', 'Noto Sans Devanagari', 'sans-serif'],
      }
    },
  },
  plugins: [],
}
